"""
main.py — niyojak AI Inference Engine
-------------------------------------
FastAPI server that the Go scheduler calls to score candidate nodes.
Matches the 18-feature schema generated by the offline pipeline.
"""

import os
import time
import logging
from contextlib import asynccontextmanager

from fastapi import FastAPI
from fastapi.responses import PlainTextResponse
from pydantic import BaseModel

from feature_store import feature_store
from model import node_scorer

# ---------------------------------------------------------------------------
# Logging
# ---------------------------------------------------------------------------
logging.basicConfig(
    level=logging.INFO,
    format="%(asctime)s [%(name)s] %(levelname)s %(message)s",
)
logger = logging.getLogger("niyojak.main")

_counters = {
    "score_requests_total": 0,
    "score_fallback_total": 0,
    "score_latency_ms_sum": 0.0,
}

# ---------------------------------------------------------------------------
# Startup / shutdown
# ---------------------------------------------------------------------------
@asynccontextmanager
async def lifespan(app: FastAPI):
    logger.info("niyojak-aiservice starting")
    feature_store.start()
    node_scorer.load()
    logger.info("niyojak-aiservice ready — scoring source: %s", node_scorer.source)
    yield
    logger.info("niyojak-aiservice shutting down")

app = FastAPI(
    title="niyojak AI Inference Engine",
    description="Real-time Kubernetes node placement scoring service (18-feature schema)",
    version="0.2.0",
    lifespan=lifespan,
)

# ---------------------------------------------------------------------------
# Request / Response schemas
# ---------------------------------------------------------------------------
class ScoreRequest(BaseModel):
    pod_name: str
    pod_namespace: str
    node_name: str
    pod_labels: dict[str, str] = {}
    cpu_request_millicores: int = 0
    memory_request_bytes: int = 0

class ScoreResponse(BaseModel):
    score: int
    reason: str
    source: str

class NodeStatus(BaseModel):
    node_name: str
    score: int
    features: dict

# ---------------------------------------------------------------------------
# Endpoints
# ---------------------------------------------------------------------------
@app.post("/score", response_model=ScoreResponse)
def score(req: ScoreRequest) -> ScoreResponse:
    t0 = time.perf_counter()

    # 1. Base Node Allocation Features (8 features)
    features = feature_store.get_features(req.node_name)
    
    # 2. Extract Pod Requirements
    requested_cpu = float(req.cpu_request_millicores)
    requested_memory = float(req.memory_request_bytes)
    
    features["requested_cpu"] = requested_cpu
    features["requested_memory"] = requested_memory
    
    # Base capacities with zero-division guards
    alloc_cpu = max(features.get("node_allocatable_cpu", 1000.0), 1.0)
    alloc_mem = max(features.get("node_allocatable_memory", 1024.0**3), 1.0)
    
    # Current usages
    curr_cpu = features.get("current_cpu_usage", 0.0)
    curr_mem = features.get("current_memory_usage", 0.0)
    curr_pod_count = features.get("current_pod_count", 0)

    # 3. Dynamic Projections (10 features)
    projected_cpu = curr_cpu + requested_cpu
    projected_memory = curr_mem + requested_memory
    
    projected_cpu_percent = projected_cpu / alloc_cpu
    projected_memory_percent = projected_memory / alloc_mem
    
    cpu_headroom = max(0.0, 1.0 - projected_cpu_percent)
    memory_headroom = max(0.0, 1.0 - projected_memory_percent)
    resource_balance = abs(cpu_headroom - memory_headroom)
    
    cpu_request_ratio = requested_cpu / alloc_cpu
    memory_request_ratio = requested_memory / alloc_mem
    
    packing_density = (curr_pod_count + 1) / 110.0

    # Inject into feature dictionary
    features["projected_cpu_percent"] = projected_cpu_percent
    features["projected_memory_percent"] = projected_memory_percent
    features["cpu_headroom"] = cpu_headroom
    features["memory_headroom"] = memory_headroom
    features["resource_balance"] = resource_balance
    features["cpu_request_ratio"] = cpu_request_ratio
    features["memory_request_ratio"] = memory_request_ratio
    features["packing_density"] = packing_density

    # 4. Predict
    raw_score, source = node_scorer.predict(features)
    final_score = int(max(0, min(100, raw_score)))

    elapsed_ms = (time.perf_counter() - t0) * 1000

    # 5. Metrics
    _counters["score_requests_total"] += 1
    _counters["score_latency_ms_sum"] += elapsed_ms
    if source == "heuristic":
        _counters["score_fallback_total"] += 1

    reason = (
        f"req_cpu={requested_cpu:.0f}m "
        f"proj_cpu%={projected_cpu_percent*100:.1f}% "
        f"headroom={cpu_headroom*100:.1f}% "
        f"latency={elapsed_ms:.2f}ms"
    )

    logger.debug(
        "scored node %s for pod %s/%s: %d/100 (%s) in %.2fms",
        req.node_name, req.pod_namespace, req.pod_name, final_score, source, elapsed_ms,
    )

    return ScoreResponse(score=final_score, reason=reason, source=source)

@app.get("/health")
def health():
    return {"status": "ok", "scoring_source": node_scorer.source}

@app.get("/nodes", response_model=list[NodeStatus])
def nodes():
    result = []
    for node_name in feature_store.known_nodes():
        features = feature_store.get_features(node_name)
        raw_score, _ = node_scorer.predict(features)
        score = int(max(0, min(100, raw_score)))
        
        # Display just the key metrics for the admin dashboard
        result.append(NodeStatus(
            node_name=node_name,
            score=score,
            features={
                "cpu_util%": round(features.get("current_cpu_percent", 0) * 100, 1),
                "mem_util%": round(features.get("current_memory_percent", 0) * 100, 1),
                "pods": features.get("current_pod_count", 0),
            },
        ))
    return result

@app.get("/metrics", response_class=PlainTextResponse)
def metrics():
    total = _counters["score_requests_total"]
    avg_latency = (_counters["score_latency_ms_sum"] / total if total > 0 else 0)
    lines = [
        "# HELP niyojak_score_requests_total Total scoring requests received",
        "# TYPE niyojak_score_requests_total counter",
        f"niyojak_score_requests_total {total}",
        "",
        "# HELP niyojak_score_fallback_total Requests answered by heuristic fallback",
        "# TYPE niyojak_score_fallback_total counter",
        f"niyojak_score_fallback_total {_counters['score_fallback_total']}",
        "",
        "# HELP niyojak_score_latency_ms_avg Average scoring latency in milliseconds",
        "# TYPE niyojak_score_latency_ms_avg gauge",
        f"niyojak_score_latency_ms_avg {avg_latency:.4f}",
    ]
    return "\n".join(lines)

if __name__ == "__main__":
    import uvicorn
    uvicorn.run(
        "main:app",
        host="0.0.0.0",
        port=int(os.getenv("PORT", "8000")),
        log_level="info",
        access_log=False,
    )
